//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDemo {
    public partial class Default {
        protected global::System.Web.UI.WebControls.Label lblSession;
    }
}




