//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrationDemo {
    public partial class Products {
        protected global::System.Web.UI.WebControls.SqlDataSource dsProducts;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.DetailsView DetailsView1;
        protected global::System.Web.UI.WebControls.Label lblAddStatus;
    }
}




